#!/bin/bash

rm -rf *.out tmp FILD3DYN
mkdir -p FILDYN FILDRHO FILD3DYN

export EXAMPLE=$(pwd)
export ESPRESSO=$(cd ../../../; pwd)
export ESPRESSO_BIN=$ESPRESSO/bin

bin="$ESPRESSO_BIN"
pref=" mpirun -np 4 "
post=" -npool 2"

echo "pw calculation"
$pref $bin/pw.x $post -in pw.in > pw.out 

echo "ph calculation"
$pref $bin/ph.x $post -in ph.in > ph.out 

echo "d3 calculation"
$pref $bin/d3q.x $post -in d3q.in > d3q.out 

echo "computing 2-body force constants"
$bin/d3_q2r.x < q2r.in > d3_q2r.out

echo "computing 3-body force constants"
ls FILD3DYN/anh* | $bin/d3_qq2rr.x 2 2 2 -o mat3R > d3_qq2rr.out

echo "appying sum rules 3-body force constants"
$bin/d3_asr3.x -i mat3R -o mat3R.asr -t 1.e-12 -n 10000 -p 2 > d3_asr3.out

echo "preparing sparse representation of 3-body force constants"
$bin/d3_sparse.x -i mat3R.asr -o mat3R.asr.sparse -t 0. -n 10000 > d3_sparse.out

echo "doing spectra function calculation"
$pref $bin/d3_lw.x -in input.SPF > output.SPF
gnuplot -persist plot-spf.gp

echo "doing final state calculation"
$pref $bin/d3_lw.x -in input.FS> output.FS
gnuplot -persist plot-fs1.gp

echo "computing phonon dispersion"
$pref $bin/d3_r2q.x > output.R2Q
gnuplot -persist plot-fs.gp
gnuplot -persist plot-projected.gp


