#!/bin/bash

rm -r *.out tmp TMP TMP3 FIL*

export EXAMPLE=$(pwd)
export ESPRESSO=$HOME/espresso

export ESPRESSO_BIN=$ESPRESSO/bin
export ESPRESSO_PSEUDO=$EXAMPLE/UPF
export ESPRESSO_TMPDIR=$EXAMPLE/TMP
export ESPRESSO_D3DIR=$EXAMPLE/TMP3
export ESPRESSO_FILDRHO_DIR=$EXAMPLE/FILDRHO

mkdir -p $ESPRESSO_TMPDIR
mkdir -p $ESPRESSO_D3DIR
mkdir -p $ESPRESSO_FILDRHO_DIR
mkdir -p $EXAMPLE/FILDYN/
mkdir -p $EXAMPLE/FILD3DYN/

bin="$ESPRESSO_BIN"
pref=" "  # e.g. "mpirun -np 4 "
post=" "  # e.g. -npool 4

echo "pw calculation"
$pref $bin/pw.x $post -in pw.in > pw.out 

echo "ph calculation"
$pref $bin/ph.x $post -in ph.in > ph.out 

echo "d3 calculation"
$pref $bin/d3q.x $post -in d3.in > d3.out 

