#!/bin/bash

rm -rf *.out tmp FILD3DYN

export EXAMPLE=$(pwd)
export ESPRESSO=$(cd ../../../; pwd)
export ESPRESSO_BIN=$ESPRESSO/bin

bin="$ESPRESSO_BIN"
pref=" "  # e.g. "mpirun -np 4 "
post=" "  # e.g. -npool 4

echo "pw calculation"
$pref $bin/pw.x $post -in pw.in > pw.out 

echo "ph calculation"
$pref $bin/ph.x $post -in ph.in > ph.out 

echo "d3 calculation"
$pref $bin/d3q.x $post -in d3.in > d3.out 

